apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-vectorchord
  namespace: immich 
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-1.1.0
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: immich
        superuser: true
        login: true
        passwordSecret:
          name: immich-postgres-user
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vchord";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  storage:
    size: 4Gi
    storageClass: longhorn 
