apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-vectorchord
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: immich
        superuser: true
        login: true
        passwordSecret:
          name: immich-postgres-user
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
  storage:
    size: 4Gi
    storageClass: longhorn 
