apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: authentik
        superuser: false
        login: true
        passwordSecret:
          name: authentik-postgresql-user
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgresql-user
  storage:
    size: 8Gi
    storageClass: longhorn
